spring:
  application:
    name: kkokio

  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_pw}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect